name = "Bouyant"
version = "0.1.0"
defaultTargets = ["bouyant"]
lean-toolchain = "leanprover/lean4:v4.15.0-rc1"


[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "master"

[[lean_lib]]
name = "Bouyant"

[[lean_exe]]
name = "bouyant"
root = "Main"

[[require]]
name = "LeanSearchClient"
git = "https://github.com/leanprover-community/LeanSearchClient.git"
rev = "main"
